config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users, :controllers => { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts, :friend_requests, :friendships, :likes, :comments, :profiles
  resources :users, only: [:index, :show]

  # get '/users/:id/edit_profile', to: 'users#edit_profile'
  # post '/users/:id/edit_profile', to: 'users#update_profile'
end

app/views/shared/_create_del_req.html.erb
<% unless user.request_from_current_user?(current_user.id) %>
  <%= button_to 'Add',
                friend_requests_path,
                method: :post,
                params: { friend_request: {requester_id: current_user.id, reciever_id: user.id} },
                class: 'button is-rounded is-primary' %>
<% else %>
  <%= button_to 'Delete',
                friend_request_path('placeholder'),
                method: :delete,
                params: {requester_id: current_user.id, reciever_id: user.id},
                class: 'button is-rounded is-danger mx-1' %>
<% end %>

app/views/shared/_delete_comment_button.html.erb
<% if current_user == comment.user %>
  <%=  link_to "Delete", 
              comment_path(comment.id),
              data: { turbo_method: :delete }
              %>
<% end %>

app/views/shared/_delete_post_button.html.erb
<% if post.author?(current_user) %>
  <%= link_to "Delete ·", 
              post_path(post.id),
              data: { turbo_method: :delete, turbo_frame: "_top" }
              %>
<% end %>

app/views/shared/_edit_delete_links.html.erb
<% if comment.author?(current_user) %>
  <%=  link_to "Edit", edit_comment_path(comment.id) %>
  <%=  link_to "· Delete", 
              comment_path(comment.id),
              data: { turbo_method: :delete, turbo_frame: '_top' }
              %>
<% end %>

app/views/shared/_edit_post_button.html.erb
<% if post.author?(current_user) %>
  <%= link_to "Edit Post", edit_post_path(post) %> ·
<% end %>

app/views/shared/_edit_prof.html.erb
<% if user == current_user %>
  <%= link_to "Edit bio", edit_profile_path(user.id) %>        
<% end %>

app/views/shared/_full_comment.html.erb
<article class="media">
  <figure class="media-left">
    <%= render "shared/profile_pic", {user: comment.user, size: "is-48x48"} %>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= link_to comment.author_name, user_path(comment.author_id) %></strong>

        <%= turbo_frame_tag comment do %>
          <br>
            <%= comment.body %>
          <br>
          <small><%= render "shared/edit_delete_links", {comment: comment} %></small>
        <% end %>

      </p>
    </div>
  </div>
</article>

app/views/shared/_full_post.html.erb
<div data-controller="toggle">
  <article class="media box">
  
    <figure class="media-left">
      <%= render "shared/profile_pic", {user: post.user, size: "is-48x48"} %>
    </figure>
  
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= link_to post.author_name, user_path(post.author_id) %></strong>
  
          <%= turbo_frame_tag post do %>
  
            <% if post.photo? %>
              <%= image_tag url_for(post.photo) %>
            <% end %>
  
            <br><%= post.body %><br>
  
            <small>
                <%= render "shared/edit_post_button", post: post %>
                <%= render "shared/delete_post_button", {current_user: current_user, post: post} %>
                <%= post.pretty_time %>
            </small>
          <% end %>
        </p>
      </div>
  
      <%= turbo_frame_tag "like_#{post.id}" do %>
        <article class="media">
          <%= render "shared/like_unlike", {post: post} %>
  
          <% if post.has_likes? %>
            <p class='mx-1'><%= post.display_likes %></p>
          <% end %>
        </article>
      <% end %>
  
      <% post.comments.each do |comment| %>
        <%= render 'shared/full_comment', comment: comment %>
      <% end %>
    </div>
  
    <article>
      <button class="js-modal-trigger button is-link is-rounded is-small" data-action="toggle#hide_unhide">
        Comment
      </button>
    </article>
  </article>
  
  <div class="modal" data-toggle-target="source">
    <div class="modal-background" data-action="click->toggle#hide_unhide"></div>
    <div class="modal-content">
      <div class="box">
        <%= render 'shared/new_comment', {comment: comment, post: post} %>
      </div>
    </div>
  
    <button class="modal-close is-large" aria-label="close" data-action="toggle#hide_unhide"></button>
  </div>
</div>

app/views/shared/_hero.html.erb
<section class="hero is-link">
  <div class="hero-body">
    <p class="title is-size-2">
      RailsBook
    </p>
    <p class="subtitle is-size-6">
      Join Today!
    </p>
  </div>
</section>

app/views/shared/_like_unlike.html.erb
<div class="mb-3">
  <% unless post.liked_by?(current_user) %>
      <%= link_to image_tag('like.png', class: 'image is-16x16'),
                  likes_path({ like: {user_id: current_user.id, post_id: post.id}}),
                  data: { turbo_method: :post },
                  class: 'has-text-primary'
                  %>
  <% else %>
      <%= link_to image_tag('dislike.png', class: 'image is-16x16'),
                  like_path({id: 0, like: {user_id: current_user.id, post_id: post.id} }),
                  data: { turbo_method: :delete },
                  class: 'has-text-danger'
                  %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar is-link" data-controller="toggle">
  <div class="navbar-brand flex" style="height: 10vh;">
    <div class="navbar-item">
      <%= link_to "RailsBook", root_path, class: "has-text-white is-size-2 has-text-weight-bold" %>
    </div>

    <a data-action="toggle#hide_unhide" role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navmenu" style='margin-top:1.5rem;'>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu" data-toggle-target="source">
    <div class="navbar-start">
      <div class="navbar-item is-hidden-touch" ><%= link_to "Home", root_path, class: 'has-text-white' %></div>
      <div class="navbar-item is-hidden-touch"><%= link_to "Add Friends", users_path, class: 'has-text-white' %></div>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link is-hidden-touch">
          <p>Profile</p>
        </a>

        <div class="navbar-dropdown ml-2 mr-2 is-hidden-touch">
          <ul>
            <li class='m-1'><%= link_to "View profile", user_path(current_user.id) %></li>
            <li class='m-1'><%= link_to "Settings", edit_user_registration_path %></li>
            <li class='m-1'><%= link_to "Add Friends", users_path %></li>
            <li class="m-1"><%= render "shared/edit_prof", {user: current_user} %></li>
          </ul>
        </div>

        <div class="navbar-dropdown ml-2 mr-2 is-hidden-desktop	">
          <ul class="is-flex is-flex-direction-row is-justify-content-space-around is-align-content-center">
            <li class='m-1'><%= link_to "View profile", user_path(current_user.id) %></li>
            <li class='m-1'><%= link_to "Settings", edit_user_registration_path %></li>
            <li class='m-1'><%= link_to "Add Friends", users_path %></li>
            <li class="m-1"><%= render "shared/edit_prof", {user: current_user} %></li>
            <li><%= button_to "Signout", destroy_user_session_path, class: "button is-danger is-small", method: :delete, data: {turbo: false} %></li> 
          </ul>
        </div>

      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link is-flex is-hidden-touch">
          <p>Friend Requests</p>
        </a>

        <div class="navbar-dropdown is-hidden-touch">
          
          <% if defined?(notifs) && notifs.empty? %>
            <a class="navbar-item is-hidden-touch">
              Nothing for now!
            </a>
          <% end %>
          
          <% if defined?(notifs) %>
            <% notifs.each do |notif| %>
                <div class="container is-flex level mx-2 p-1">
                  <%= link_to notif.display_name, user_path(notif.id) %>
                  <%= render 'shared/accept_reject_req', user: notif %>
                </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="navbar-item is-hidden-touch"><%= button_to "Signout", destroy_user_session_path, class: "button is-danger", method: :delete, data: {turbo: false} %></div>
    </div>
  </div>
</div>

app/views/shared/_new_comment.html.erb
<%= form_with model: comment, class: "is-flex is-flex-direction-column is-align-items-center" do |f| %>
  <%= f.hidden_field :post_id, value: post.id %>

  <div class="container has-text-centered">
    <%= f.label :body, "New Comment", class: 'label' %>
    <%= f.text_area :body, cols: 50, placeholder: "What's going on?", class: 'textarea' %>
    <%= f.submit 'Comment', class: 'button my-2 is-rounded is-link' %>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<div class="container is-flex is-flex-direction-column is-align-items-center m-5">
  <h2 class="title">New Post</h2>

  <%= form_with model: model, class: 'is-flex is-flex-direction-column is-align-items-center', method: "post" do |f| %>
    <%= f.text_area :body, cols: 50, rows: 3, placeholder: "What's going on?", class: 'textarea is-hovered has-background-white-bis'%>
    <%= f.file_field :photo, class: 'file mt-4' %>
    <%= f.submit "Submit Post", class: 'button mt-4 is-rounded is-link' %>
  <% end %>
</div>

app/views/shared/_profile_pic.html.erb
<figure class="is-inline-block image <%= size %>" >  
  <% if user.profile_pic? %>
    <%= image_tag url_for(user.profile_picture), class: "is-rounded" %>
  <% else %>
    <%= image_tag "prof-placeholder.png", class: "is-rounded" %>
  <% end %>
</figure>